title: Hridhya Raveendran
email: hridhyaraveendranp2000@gmail.com
phone: +91 7034725988
description: Sound Recordist and Designer based in Kerala. A graduate of the prestigious Satyajit Ray Film and Television Institute, I bring a strong foundation in both technical expertise and artistic vision to every project I undertake.
baseurl: ""
url: "https://www.instagram.com/hridhya_raveendran?igsh=eDdqcWY0amQyb3M2"
instagram_username: "hridhya_raveendran"
